### ISSUE TITLE
[Bug] Install Exception On Macosx

### ISSUE THREAD

**Issue by Talbot3** [apache/rocketmq-client-nodejs#17]
## What Happens?

> install error

## Minimum Showcase (Required)

> Provide a minimum code or GitHub repository which can reproduce the issue.
// node version:  v12.16.2
npm i apache-rocketmq --rebuild
## How to Reproduce
```
$ npm i apache-rocketmq --rebuild
> apache-rocketmq@1.0.0-rc1 install /Users/Arthur/FlyLab/examples/demo-rocketmq/node_modules/apache-rocketmq
> node ./script/download_lib.js && node-gyp rebuild

[rocketmq sdk] [info] downloading [https://opensource-rocketmq-client.oss-cn-hangzhou.aliyuncs.com/cpp-client/mac/1.2.0/librocketmq.dylib]...
[rocketmq sdk] [info] downloaded library [https://opensource-rocketmq-client.oss-cn-hangzhou.aliyuncs.com/cpp-client/mac/1.2.0/librocketmq.dylib].
[rocketmq sdk] [info] all libraries have been written to disk.
  CXX(target) Release/obj.target/rocketmq/src/rocketmq.o
../src/rocketmq.cpp:42:116: error: too few arguments to function call, single argument 'context' was not specified
    Nan::Set(target, Nan::New("macosDLOpen").ToLocalChecked(), Nan::New<v8::FunctionTemplate>(DLOpen)->GetFunction());
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/Arthur/Library/Caches/node-gyp/12.16.2/include/node/v8.h:6126:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/Arthur/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
1 error generated.
make: *** [Release/obj.target/rocketmq/src/rocketmq.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Arthur/FlyLab/examples/demo-rocketmq/node_modules/apache-rocketmq
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN @sevenryze/mediator@5.3.0 requires a peer of @nestjs/common@^7.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN @sevenryze/mediator@5.3.0 requires a peer of @nestjs/core@^7.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN @sevenryze/mediator@5.3.0 requires a peer of reflect-metadata@^0.1.13 but none is installed. You must install peer dependencies yourself.
npm WARN @sevenryze/mediator@5.3.0 requires a peer of rxjs@^6.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN demo-rocketmq@1.0.0 No description
npm WARN demo-rocketmq@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apache-rocketmq@1.0.0-rc1 install: `node ./script/download_lib.js && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apache-rocketmq@1.0.0-rc1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
**Steps to reproduce the behavior:**

1.sudo n lts
2.npm i apache-rocketmq --rebuild

**Expected behavior**

install success

## Context

- **Node Version**: v12.16.2
- **SDK Version**: 1.0.0-rc1
- **Platform**: macos

**Comment by Talbot3** [comment]
same with #12

**Comment by xiejunping** [comment]
同样 使用mac也是安装不成功，但是这个要在服务器上跑的，即使是mac成功了，也不能上线使用，只是想学习一下，发现困难丛丛

**Comment by ifplusor** [comment]
An N-API version is available in [n-api branch](https://github.com/apache/rocketmq-client-nodejs), which supports macOS and Linux.
